export const GET_SOURCES_FETCH = 'GET_SOURCES_FETCH';
export const GET_SOURCES_SUCCESS = 'GET_SOURCES_SUCCESS';
export const GET_SOURCES_FROM_CACHE = 'GET_SOURCES_FROM_CACHE';
export const GET_SOURCES_ERROR = 'GET_SOURCES_ERROR';
export const FILTER_SOURCES = 'FILTER_SOURCES';

export const GET_NEWS_FETCH = 'GET_NEWS_FETCH';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FROM_CACHE = 'GET_NEWS_FROM_CACHE';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';
